# 1. Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 2.Load data

In [2]:
df1 = pd.read_excel("C:\\Users\\DELL\\Downloads\\online_retail_II.xlsx",
                    sheet_name="Year 2009-2010")
df2 = pd.read_excel("C:\\Users\\DELL\\Downloads\\online_retail_II.xlsx",
                    sheet_name="Year 2010-2011")

# 3.EDA

In [3]:
df1.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df1.info()
print('shape ', df1.shape)
print('columns ', list(df1.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB
shape  (525461, 8)
columns  ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [6]:
df2.info()
print('shape ', df2.shape)
print('columns ', list(df2.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
shape  (541910, 8)
columns  ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [7]:
df1.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [8]:
df2.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,541910.000000,541910,541910.000000,406830.000000
mean,9.552234,2011-07-04 13:35:22.342307584,4.611138,15287.684160
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.080957,NaN,96.759765,1713.603074

In [9]:
print("total number of transaction:",(~df1.duplicated()).sum())

total number of transaction: 518596

In [10]:
print("total number of transaction:",(~df2.duplicated()).sum())

total number of transaction: 536642

In [11]:
print("number of unique customers 1:",df1['Customer ID'].nunique())
print("number of unique customers 2:",df2['Customer ID'].nunique())

number of unique customers 1: 4383
number of unique customers 2: 4372

In [12]:
print("number of unique product 1:",df1['StockCode'].nunique())
print("number of unique product 2:",df2['StockCode'].nunique())

number of unique product 1: 4632
number of unique product 2: 4070

In [13]:
print("number of unique Country 1:",df1['Country'].nunique())
print("number of unique Country 2:",df2['Country'].nunique())

number of unique Country 1: 40
number of unique Country 2: 38

In [14]:
df1["Country"].unique()

array(['United Kingdom', 'France', 'USA', 'Belgium', 'Australia', 'EIRE',
       'Germany', 'Portugal', 'Japan', 'Denmark', 'Nigeria',
       'Netherlands', 'Poland', 'Spain', 'Channel Islands', 'Italy',
       'Cyprus', 'Greece', 'Norway', 'Austria', 'Sweden',
       'United Arab Emirates', 'Finland', 'Switzerland', 'Unspecified',
       'Malta', 'Bahrain', 'RSA', 'Bermuda', 'Hong Kong', 'Singapore',
       'Thailand', 'Israel', 'Lithuania', 'West Indies', 'Lebanon',
       'Korea', 'Brazil', 'Canada', 'Iceland'], dtype=object)

In [15]:
df1["InvoiceDate"] = pd.to_datetime(df1["InvoiceDate"])
print(df1["InvoiceDate"].max() - df1["InvoiceDate"].min())

373 days 12:16:00

In [16]:
df2["InvoiceDate"] = pd.to_datetime(df2["InvoiceDate"])
print(df2["InvoiceDate"].max() - df2["InvoiceDate"].min())

373 days 04:24:00

In [17]:
df1[df1["Price"]==0].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
5904,489861,DOT,DOTCOM POSTAGE,1,2009-12-02 14:50:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom

In [18]:
# canceled1=df1["Invoice"].astype(str).str[0]=='C'
print(df1[df1["Invoice"].astype(str).str[0]=='C'].head())
print("cancelled:",len(df1[df1["Invoice"].astype(str).str[0]=='C']))
# df1_canceled=df1[canceled1]

     Invoice StockCode                    Description  Quantity  \
178  C489449     22087       PAPER BUNTING WHITE LACE       -12
179  C489449    85206A   CREAM FELT EASTER EGG BASKET        -6
180  C489449     21895  POTTING SHED SOW 'N' GROW SET        -4
181  C489449     21896             POTTING SHED TWINE        -6
182  C489449     22083     PAPER CHAIN KIT RETRO SPOT       -12

            InvoiceDate  Price  Customer ID    Country
178 2009-12-01 10:33:00   2.95      16321.0  Australia
179 2009-12-01 10:33:00   1.65      16321.0  Australia
180 2009-12-01 10:33:00   4.25      16321.0  Australia
181 2009-12-01 10:33:00   2.10      16321.0  Australia
182 2009-12-01 10:33:00   2.95      16321.0  Australia
cancelled: 10206

In [19]:
# canceled2=df2["Invoice"].astype(str).str[0]=='C'
print(df2[df2["Invoice"].astype(str).str[0]=='C'].head())
print("cancelled:",len(df2[df2["Invoice"].astype(str).str[0]=='C']))
# df2_canceled=df2[canceled2]

     Invoice StockCode                       Description  Quantity  \
141  C536379         D                          Discount        -1
154  C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235  C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236  C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237  C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24

            InvoiceDate  Price  Customer ID         Country
141 2010-12-01 09:41:00  27.50      14527.0  United Kingdom
154 2010-12-01 09:49:00   4.65      15311.0  United Kingdom
235 2010-12-01 10:24:00   1.65      17548.0  United Kingdom
236 2010-12-01 10:24:00   0.29      17548.0  United Kingdom
237 2010-12-01 10:24:00   0.29      17548.0  United Kingdom
cancelled: 9288

In [20]:
print(df1.duplicated().sum())
print(df2.duplicated().sum())

6865
5268

In [21]:
df1.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [22]:
df2.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [23]:
num_cols1 = df1.select_dtypes(include=np.number).columns.tolist()
num_cols2 = df2.select_dtypes(include=np.number).columns.tolist()
print(num_cols1)
print(num_cols2)

['Quantity', 'Price', 'Customer ID']
['Quantity', 'Price', 'Customer ID']

In [24]:
for col in num_cols1:
    Q1 = df1[col].quantile(0.25)
    Q3 = df1[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df1[(df1[col] < lower) | (df1[col] > upper)]

    if len(outliers) > 0:
        print(col)
        print(len(outliers))

Quantity
57870
Price
35273

In [25]:
for col in num_cols2:
    Q1 = df2[col].quantile(0.25)
    Q3 = df2[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df2[(df2[col] < lower) | (df2[col] > upper)]

    if len(outliers) > 0:
        print(col)
        print(len(outliers))

Quantity
58619
Price
39628

In [26]:
print(df1[df1["Price"]<0])
print(df2[df2["Price"]<0])

        Invoice StockCode      Description  Quantity         InvoiceDate  \
179403  A506401         B  Adjust bad debt         1 2010-04-29 13:36:00
276274  A516228         B  Adjust bad debt         1 2010-07-19 11:24:00
403472  A528059         B  Adjust bad debt         1 2010-10-20 12:04:00

           Price  Customer ID         Country
179403 -53594.36          NaN  United Kingdom
276274 -44031.79          NaN  United Kingdom
403472 -38925.87          NaN  United Kingdom
        Invoice StockCode      Description  Quantity         InvoiceDate  \
299983  A563186         B  Adjust bad debt         1 2011-08-12 14:51:00
299984  A563187         B  Adjust bad debt         1 2011-08-12 14:52:00

           Price  Customer ID         Country
299983 -11062.06          NaN  United Kingdom
299984 -11062.06          NaN  United Kingdom

In [27]:
print("Quantity of cancelled orders:")
print(df1[(df1["Quantity"] < 0) & (df1["Invoice"].astype(str).str[0] == "C")])

Quantity of cancelled orders:
        Invoice StockCode                       Description  Quantity  \
178     C489449     22087          PAPER BUNTING WHITE LACE       -12
179     C489449    85206A      CREAM FELT EASTER EGG BASKET        -6
180     C489449     21895     POTTING SHED SOW 'N' GROW SET        -4
181     C489449     21896                POTTING SHED TWINE        -6
182     C489449     22083        PAPER CHAIN KIT RETRO SPOT       -12
...         ...       ...                               ...       ...
524695  C538123     22956          36 FOIL HEART CAKE CASES        -2
524696  C538124         M                            Manual        -4
524697  C538124     22699  ROSES REGENCY TEACUP AND SAUCER         -1
524698  C538124     22423          REGENCY CAKESTAND 3 TIER        -1
525282  C538164    35004B       SET OF 3 BLACK FLYING DUCKS        -1

               InvoiceDate  Price  Customer ID         Country
178    2009-12-01 10:33:00   2.95      16321.0       Australia
179    2009-12-01 10:33:00   1.65      16321.0       Australia
180    2009-12-01 10:33:00   4.25      16321.0       Australia
181    2009-12-01 10:33:00   2.10      16321.0       Australia
182    2009-12-01 10:33:00   2.95      16321.0       Australia
...                    ...    ...          ...             ...
524695 2010-12-09 15:41:00   2.10      12605.0         Germany
524696 2010-12-09 15:43:00   0.50      15329.0  United Kingdom
524697 2010-12-09 15:43:00   2.95      15329.0  United Kingdom
524698 2010-12-09 15:43:00  12.75      15329.0  United Kingdom
525282 2010-12-09 17:32:00   1.95      14031.0  United Kingdom

[10205 rows x 8 columns]

In [28]:
print(
    (df1["Quantity"] < 0).equals(
        df1["Invoice"].astype(str).str[0]=='C'
    )
)
print("inconsistent1:",df1[    (df1["Quantity"] < 0)
    & (~df1["Invoice"].astype(str).str.startswith("C"))])

False
inconsistent1:        Invoice StockCode   Description  Quantity         InvoiceDate  Price  \
263     489464     21733  85123a mixed       -96 2009-12-01 10:52:00    0.0
283     489463     71477         short      -240 2009-12-01 10:52:00    0.0
284     489467    85123A   21733 mixed      -192 2009-12-01 10:53:00    0.0
470     489521     21646           NaN       -50 2009-12-01 11:44:00    0.0
3114    489655     20683           NaN       -44 2009-12-01 17:26:00    0.0
...        ...       ...           ...       ...                 ...    ...
524458  538092     37467           NaN      -177 2010-12-09 14:49:00    0.0
525231  538159     21324           NaN       -18 2010-12-09 17:17:00    0.0
525232  538158     20892           NaN       -32 2010-12-09 17:17:00    0.0
525234  538161    46000S  Dotcom sales      -100 2010-12-09 17:25:00    0.0
525235  538162    46000M  Dotcom sales      -100 2010-12-09 17:25:00    0.0

        Customer ID         Country
263             NaN  United Kingdom
283             NaN  United Kingdom
284             NaN  United Kingdom
470             NaN  United Kingdom
3114            NaN  United Kingdom
...             ...             ...
524458          NaN  United Kingdom
525231          NaN  United Kingdom
525232          NaN  United Kingdom
525234          NaN  United Kingdom
525235          NaN  United Kingdom

[2121 rows x 8 columns]

In [29]:
print("Quantity of cancelled orders:")
print(df2[(df2["Quantity"] < 0) & (df2["Invoice"].astype(str).str[0] == "C")])

Quantity of cancelled orders:
        Invoice StockCode                       Description  Quantity  \
141     C536379         D                          Discount        -1
154     C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235     C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236     C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237     C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24
...         ...       ...                               ...       ...
540449  C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11
541541  C581499         M                            Manual        -1
541715  C581568     21258        VICTORIAN SEWING BOX LARGE        -5
541716  C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1
541717  C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5

               InvoiceDate   Price  Customer ID         Country
141    2010-12-01 09:41:00   27.50      14527.0  United Kingdom
154    2010-12-01 09:49:00    4.65      15311.0  United Kingdom
235    2010-12-01 10:24:00    1.65      17548.0  United Kingdom
236    2010-12-01 10:24:00    0.29      17548.0  United Kingdom
237    2010-12-01 10:24:00    0.29      17548.0  United Kingdom
...                    ...     ...          ...             ...
540449 2011-12-09 09:57:00    0.83      14397.0  United Kingdom
541541 2011-12-09 10:28:00  224.69      15498.0  United Kingdom
541715 2011-12-09 11:57:00   10.95      15311.0  United Kingdom
541716 2011-12-09 11:58:00    1.25      17315.0  United Kingdom
541717 2011-12-09 11:58:00    1.25      17315.0  United Kingdom

[9288 rows x 8 columns]

In [30]:
print(
    (df2["Quantity"] < 0).equals(
        df2["Invoice"].astype(str).str[0]=='C'
    )
)
print("inconsistent2:",df2[    (df2["Quantity"] < 0)
    & (~df2["Invoice"].astype(str).str.startswith("C"))])

False
inconsistent2:        Invoice StockCode Description  Quantity         InvoiceDate  Price  \
2406    536589     21777         NaN       -10 2010-12-01 16:50:00    0.0
4347    536764    84952C         NaN       -38 2010-12-02 14:42:00    0.0
7188    536996     22712         NaN       -20 2010-12-03 15:30:00    0.0
7189    536997     22028         NaN       -20 2010-12-03 15:30:00    0.0
7190    536998     85067         NaN        -6 2010-12-03 15:30:00    0.0
...        ...       ...         ...       ...                 ...    ...
535333  581210     23395       check       -26 2011-12-07 18:36:00    0.0
535335  581212     22578        lost     -1050 2011-12-07 18:38:00    0.0
535336  581213     22576       check       -30 2011-12-07 18:38:00    0.0
536910  581226     23090     missing      -338 2011-12-08 09:56:00    0.0
538925  581422     23169     smashed      -235 2011-12-08 15:24:00    0.0

        Customer ID         Country
2406            NaN  United Kingdom
4347            NaN  United Kingdom
7188            NaN  United Kingdom
7189            NaN  United Kingdom
7190            NaN  United Kingdom
...             ...             ...
535333          NaN  United Kingdom
535335          NaN  United Kingdom
535336          NaN  United Kingdom
536910          NaN  United Kingdom
538925          NaN  United Kingdom

[1336 rows x 8 columns]

In [31]:
print(df2[(df2["Price"] < 0) & (df2["Invoice"].astype(str).str[0] == "C")])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [32]:
print("price :")
print(df1[df1["Price"] < 0])

price :
        Invoice StockCode      Description  Quantity         InvoiceDate  \
179403  A506401         B  Adjust bad debt         1 2010-04-29 13:36:00
276274  A516228         B  Adjust bad debt         1 2010-07-19 11:24:00
403472  A528059         B  Adjust bad debt         1 2010-10-20 12:04:00

           Price  Customer ID         Country
179403 -53594.36          NaN  United Kingdom
276274 -44031.79          NaN  United Kingdom
403472 -38925.87          NaN  United Kingdom

In [33]:
customer_prc1 = df1.groupby("Customer ID")["Price"].sum()
print(customer_prc1[customer_prc1 < 0])

Series([], Name: Price, dtype: float64)

# 4.cleaning

In [34]:
#drop dublicates
df1 = df1.drop_duplicates().reset_index(drop=True)
print(df1.duplicated().sum())

0

In [35]:
#drop dublicates
df2 = df2.drop_duplicates().reset_index(drop=True)
print(df2.duplicated().sum())

0

In [36]:
# fill Description
df1["Description"] = df1["Description"].fillna(
    df1.groupby("StockCode")["Description"].transform("first")
)
print(df1.isnull().sum())

Invoice             0
StockCode           0
Description       365
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

In [37]:
# fill null Description
df1["Description"] = df1["Description"].fillna("unknown")
print(df1.isnull().sum())

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

In [38]:
# fill Description
df2["Description"] = df2["Description"].fillna(
    df2.groupby("StockCode")["Description"].transform("first")
)
print(df2.isnull().sum())

Invoice             0
StockCode           0
Description       112
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135037
Country             0
dtype: int64

In [39]:
# fill null Description
df2["Description"] = df2["Description"].fillna("unknown")
print(df2.isnull().sum())

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135037
Country             0
dtype: int64

In [40]:
# handle customer id 
df1["Customer ID"] = df1["Customer ID"].fillna(-1)
print(df1.isnull().sum())

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [41]:
# handle customer id 
df2["Customer ID"] = df2["Customer ID"].fillna(-1)
print(df2.isnull().sum())

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [42]:
#make price zero=null
df1["Price"] = df1["Price"].replace(0,np.nan)
df2["Price"] = df2["Price"].replace(0,np.nan)

In [43]:
print(len(df1[df1["Price"] == 0]))
print(len(df2[df2["Price"] == 0]))

0
0

In [44]:
print(df1.isnull().sum())
print(df2.isnull().sum())

Invoice           0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
Price          3681
Customer ID       0
Country           0
dtype: int64
Invoice           0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
Price          2510
Customer ID       0
Country           0
dtype: int64

In [45]:
# fill zero price
df1["Price"] = df1["Price"].fillna(
    df1.groupby(["StockCode","Description"])["Price"].transform("first")
)
df2["Price"] = df2["Price"].fillna(
    df2.groupby(["StockCode","Description"])["Price"].transform("first")
)

In [46]:
print(df1.isnull().sum())
print(df2.isnull().sum())

Invoice          0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
Price          714
Customer ID      0
Country          0
dtype: int64
Invoice          0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
Price          756
Customer ID      0
Country          0
dtype: int64

In [47]:
df1["Price"] = df1["Price"].fillna(0)
df2["Price"] = df2["Price"].fillna(0)

In [48]:
print(df1.isnull().sum())
print(df2.isnull().sum())

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [49]:
#remove inconsistent value
inconsistent1 = (df1["Quantity"] < 0) & (~df1["Invoice"].astype(str).str.startswith("C"))
df1 = df1[~inconsistent1].copy()

In [50]:
#check  inconsistent value
print(len(df1[inconsistent1]))

0

C:\Users\DELL\AppData\Local\Temp\ipykernel_28564\903306622.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df1[inconsistent1]))

In [51]:
#remove inconsistent value(negative)
inconsistent2 = (df2["Quantity"] < 0) & (~df2["Invoice"].astype(str).str.startswith("C"))
df2 = df2[~inconsistent2].copy()

In [52]:
#check inconsistent value(negative)
print(len(df2[inconsistent2]))

0

C:\Users\DELL\AppData\Local\Temp\ipykernel_28564\2066147119.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df2[inconsistent2]))

In [53]:
#drop negative price
df1 = df1[df1["Price"] > 0].copy()
df2 = df2[df2["Price"] > 0].copy()

In [54]:
#check negative price
df1[df1["Price"]<0]
df2[df2["Price"]<0]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [55]:
 #handle positive value in cancel
df1.loc[(df1["Invoice"].str.startswith("C", na=False)) & (df1["Quantity"] > 0), "Quantity"] *= -1
df2.loc[(df2["Invoice"].str.startswith("C", na=False)) & (df2["Quantity"] > 0), "Quantity"] *= -1

In [56]:
#standarizing fields
df1["Country"] = df1["Country"].replace("EIRE", "Ireland")
df2["Country"] = df2["Country"].replace("EIRE", "Ireland")
df1["Country"] = df1["Country"].replace("RSA", "South Africa")
df2["Country"] = df2["Country"].replace("RSA", "South Africa")
df1["Country"] = df1["Country"].replace("USA", "United States")
df2["Country"] = df2["Country"].replace("USA", "United States")

In [57]:
#separate dataframes from cancel
canceled1 = df1["Invoice"].astype(str).str.startswith("C")
canceled2 = df2["Invoice"].astype(str).str.startswith("C")

df1_canceled = df1[canceled1]
df2_canceled = df2[canceled2]

df1 = df1[~canceled1]
df2 = df2[~canceled2]

In [58]:
#check dataframes from cancel
print(df1["Invoice"].astype(str).str.startswith("C").sum())
print(df2["Invoice"].astype(str).str.startswith("C").sum())

0
0

In [59]:
#final shape
print(df1.shape)
print(df2.shape)

(506181, 8)
(525870, 8)

# integration

In [60]:
df= pd.concat([df1, df2], ignore_index=True)
df_canceled=pd.concat([df1_canceled, df2_canceled], ignore_index=True)

In [61]:
print(df.shape)
print(df.head())

(1032051, 8)
  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

          InvoiceDate  Price  Customer ID         Country
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [62]:
print(df_canceled.shape)
print(df_canceled.head())

(19433, 8)
   Invoice StockCode                    Description  Quantity  \
0  C489449     22087       PAPER BUNTING WHITE LACE       -12
1  C489449    85206A   CREAM FELT EASTER EGG BASKET        -6
2  C489449     21895  POTTING SHED SOW 'N' GROW SET        -4
3  C489449     21896             POTTING SHED TWINE        -6
4  C489449     22083     PAPER CHAIN KIT RETRO SPOT       -12

          InvoiceDate  Price  Customer ID    Country
0 2009-12-01 10:33:00   2.95      16321.0  Australia
1 2009-12-01 10:33:00   1.65      16321.0  Australia
2 2009-12-01 10:33:00   4.25      16321.0  Australia
3 2009-12-01 10:33:00   2.10      16321.0  Australia
4 2009-12-01 10:33:00   2.95      16321.0  Australia

In [63]:
print(df.duplicated().sum())
print(df_canceled.duplicated().sum())

21750
329

In [64]:
#drop duplicates
df=df.drop_duplicates()
df_canceled=df_canceled.drop_duplicates()

In [65]:
print(df.duplicated().sum())
print(df_canceled.duplicated().sum())

0
0

In [66]:
#final shape
print(df.shape)
print(df_canceled.shape)

(1010301, 8)
(19104, 8)

# Export as CSV

In [67]:
df.to_csv("NTI_cleaned_final.csv",index=False)

In [68]:
df_canceled.to_csv("NTI_canceled_cleaned_final.csv",index=False)

# check

In [69]:
print(df[df["StockCode"]== "B"])

        Invoice StockCode      Description  Quantity         InvoiceDate  \
797427  A563185         B  Adjust bad debt         1 2011-08-12 14:50:00

           Price  Customer ID         Country
797427  11062.06         -1.0  United Kingdom

In [70]:
print(df[df["Price"]<0 ])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [71]:
import pandas as pd
df_check = pd.read_csv("NTI_cleaned_final.csv")

print("canceled invoice:", df_check["Invoice"].str.startswith("C").sum())

C:\Users\DELL\AppData\Local\Temp\ipykernel_28564\903360901.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_check = pd.read_csv("NTI_cleaned_final.csv")

canceled invoice: 0

In [72]:
df_check2 = pd.read_csv("NTI_canceled_cleaned_final.csv")
print(df_check2[df_check2["Quantity"]>0])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [73]:
print(df_check[df_check["Quantity"]<0])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [74]:
print(df_check[df_check["Description"]=="?"])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [75]:
print(df_check[df_check["Price"]== 0.0])

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [76]:
df_check.shape

(1010301, 8)